# Generated by Django 5.2.13 on 2026-05-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='githuboauthstate',
            new_name='accounts_gi_expires_897bbb_idx',
            old_name='accounts_gi_expires_3f8a9d_idx',
        ),
        migrations.RenameIndex(
            model_name='refreshtoken',
            new_name='accounts_re_token_h_09e29f_idx',
            old_name='accounts_re_token_h_2c1e4b_idx',
        ),
    ]
