"""ISO-3166 alpha-2 codes mapped to display names for APIs and NL parsing."""


COUNTRY_ID_TO_NAME: dict[str, str] = {
    'AO': 'Angola',
    'AU': 'Australia',
    'BF': 'Burkina Faso',
    'BI': 'Burundi',
    'BJ': 'Benin',
    'BR': 'Brazil',
    'BW': 'Botswana',
    'CA': 'Canada',
    'CD': 'DR Congo',
    'CF': 'Central African Republic',
    'CG': 'Republic of the Congo',
    'CI': "Côte d'Ivoire",
    'CM': 'Cameroon',
    'CN': 'China',
    'CV': 'Cape Verde',
    'DE': 'Germany',
    'DJ': 'Djibouti',
    'DZ': 'Algeria',
    'EG': 'Egypt',
    'EH': 'Western Sahara',
    'ER': 'Eritrea',
    'ET': 'Ethiopia',
    'FR': 'France',
    'GA': 'Gabon',
    'GB': 'United Kingdom',
    'GH': 'Ghana',
    'GM': 'Gambia',
    'GN': 'Guinea',
    'GQ': 'Equatorial Guinea',
    'GW': 'Guinea-Bissau',
    'IN': 'India',
    'JP': 'Japan',
    'KE': 'Kenya',
    'KM': 'Comoros',
    'LR': 'Liberia',
    'LS': 'Lesotho',
    'LY': 'Libya',
    'MA': 'Morocco',
    'MG': 'Madagascar',
    'ML': 'Mali',
    'MR': 'Mauritania',
    'MU': 'Mauritius',
    'MW': 'Malawi',
    'MZ': 'Mozambique',
    'NA': 'Namibia',
    'NE': 'Niger',
    'NG': 'Nigeria',
    'RW': 'Rwanda',
    'SC': 'Seychelles',
    'SD': 'Sudan',
    'SL': 'Sierra Leone',
    'SN': 'Senegal',
    'SO': 'Somalia',
    'SS': 'South Sudan',
    'ST': 'São Tomé and Príncipe',
    'SZ': 'Eswatini',
    'TD': 'Chad',
    'TG': 'Togo',
    'TN': 'Tunisia',
    'TZ': 'Tanzania',
    'UG': 'Uganda',
    'US': 'United States',
    'ZA': 'South Africa',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe',
}

def country_name_for_id(country_id: str) -> str | None:
    return COUNTRY_ID_TO_NAME.get(country_id.upper())