# Generated by Django 5.2.13 on 2026-04-14 22:35

import classify.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=classify.uuid7.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "name_normalized",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("gender", models.CharField(max_length=32)),
                ("gender_probability", models.FloatField()),
                ("sample_size", models.PositiveIntegerField()),
                ("age", models.PositiveSmallIntegerField()),
                ("age_group", models.CharField(max_length=32)),
                ("country_id", models.CharField(max_length=8)),
                ("country_probability", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
