# Generated by Django 5.2.13 on 2026-04-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classify", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="name_normalized",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="sample_size",
        ),
        migrations.AddField(
            model_name="profile",
            name="country_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age_group",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country_id",
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender_probability",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["country_id", "age_group", "gender"],
                name="classify_pr_country_3fff16_idx",
            ),
        ),
    ]
