# Generated by Django 5.2.13 on 2026-05-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_profile_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country_probability',
            field=models.FloatField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-created_at', '-id'], name='classify_pr_created_6d5a0e_idx'),
        ),
    ]
